### ISSUE TITLE
Add outputs surfacing service endpoints and ips for each vpe

### ISSUE THREAD

**Issue by vburckhardt** [terraform-ibm-modules/terraform-ibm-vpe-module#313]
### Description

There is currently no outputs in the module making it difficult to consume in a broader solution.

Add:
- List of [service endpoint](https://registry.terraform.io/providers/IBM-Cloud/ibm/latest/docs/resources/is_virtual_endpoint_gateway#service_endpoints)
 For instance
```
output "vpe_service_endpoint" {
  description = "Vpe Service Endpoint"
  value = [for vpe_pg in ibm_is_virtual_endpoint_gateway.vpe : vpe_pg.service_endpoints[0]]
  //value = { for k, vpe in ibm_is_virtual_endpoint_gateway.vpe : k => vpe.service_endpoints[0] }
}
```

- List of IPs for each VPE. https://registry.terraform.io/providers/IBM-Cloud/ibm/latest/docs/resources/is_virtual_endpoint_gateway#ips

### New or affected modules

---

By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/terraform-ibm-modules/documentation/blob/main/CODE_OF_CONDUCT.md)

**Comment by Aayush-Abhyarthi** [comment]
<img width="1058" alt="Screenshot 2023-05-29 at 2 51 35 PM" src="https://github.com/terraform-ibm-modules/terraform-ibm-vpe-module/assets/122350533/131c2ba6-0703-4766-8881-33af1f366729">

It seems like the service_endpoints is not an attribute

**Comment by vburckhardt** [comment]
@Aayush-Abhyarthi - Example is coming from customer. It is mainly to give an idea on what customer is asking for as output. Implementation details are left to us.
